name: Run FirstTest

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:

  test1:

    runs-on: ubuntu-latest

    steps:

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ github.repository }}/selenium-framework:latest

      - name: Run FirstTest
        run: |
          docker run ghcr.io/${{ github.repository }}/selenium-framework:latest \
          mvn test -Dtest=FirstTest